app = "baobaolebot"
primary_region = "sin" # 👈 这里强制改为新加坡

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # 👈 禁止休眠
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[swap_size_mb]
  size = 512
